### ISSUE TITLE
상수로 고고

### ISSUE THREAD

**Issue by 2woongjae** [Stock-Flow/stockflow#31]
https://github.com/Stock-Flow/stockflow/blob/dbe343d06df95abe4faed04a51cdd661e6de0a54/src/containers/MainDjia/djiagraphContainer.jsx#L11

**Comment by jihyeon-Do** [comment]
DataProcessingService 파일로 변수를 옮기고 함수 밖으로 빼내어 재할당되지 않도록 함

**Comment by SaltPepperSalt** [comment]
fixed let to const
